[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ctrlc = "3.4.4"
nix = { version = "0.29.0", features = ["signal"] }
rustyline = { version = "14.0.0", features = ["with-fuzzy", "derive"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
